Local update
NethermindEth/eigenlayer pull request #98
Opened 2023-10-10 12:00 UTC by adriantpaez

## Changes:

- Fix: instance name in local-install
- Fix: change run instance log in update command
- Fix: clear temp directory instead of return an error if the temp directory already exists
- Feat: add local-update command

## Types of changes

- Bugfix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## Testing

**Requires testing** Yes

**In case you checked yes, did you write tests?** No (WIP)

2023-10-10 16:12 UTC, AntiD2ta requested changes

2023-10-10 16:12 UTC, AntiD2ta commented on cli/local_update.go
> +!!! THIS INSTALLATION METHOD IS INSECURE !!!
```suggestion
!!! THIS UPDATE METHOD IS INSECURE !!!
```

2023-10-10 16:12 UTC, AntiD2ta commented on e2e/local_update_test.go
> +			assert.NoError(t, updateError, "update command should succeed")
It would be great to check if the instance is running on the new version. Please make sure all the update test cases including the old ones have such a check

2023-10-10 16:12 UTC, AntiD2ta commented on e2e/local_update_test.go
> +			updateError = runCommand(t, egnPath, "local-update", "--no-prompt", "--option.test-option-hidden", "12345678", "mock-avs-default", pkgDir)
why are you using an option flag for `test-option-hidden` and not for `test-option-enum-hidden`?

2023-10-10 16:12 UTC, AntiD2ta commented on internal/data/datadir.go
> +	// Clear temp dir if it already exists
Do you think is worth it to log that the temp dir was existing and we are deleting it? Perphaps DEBUG level?

2023-10-10 16:12 UTC, AntiD2ta commented on pkg/daemon/egn_daemon.go
> +	// designed for development purposes.
👍

2023-10-10 16:13 UTC, AntiD2ta requested changes
Please address comments and update the Changelog

2023-10-10 17:27 UTC, adriantpaez commented on e2e/local_update_test.go
> +			updateError = runCommand(t, egnPath, "local-update", "--no-prompt", "--option.test-option-hidden", "12345678", "mock-avs-default", pkgDir)
Test is updating from version `v5.4.0` to the current latest version `v5.5.1`. In `v5.5.1`, two new options, `test-option-hidden` and `test-option-enum-hidden`, are introduced that were not present in `v5.4.0`. Therefore, values need to be set for these new options.

2023-10-10 17:28 UTC, adriantpaez commented on internal/data/datadir.go
> +	// Clear temp dir if it already exists
A debug log could be useful, I agree

2023-10-10 17:49 UTC, adriantpaez commented on cli/local_update.go
> +!!! THIS INSTALLATION METHOD IS INSECURE !!!
Done https://github.com/NethermindEth/eigenlayer/pull/98/commits/5bbc0ebd3bf0cfee11b8cb9d7cd1518587815c77

2023-10-10 17:49 UTC, adriantpaez commented on internal/data/datadir.go
> +	// Clear temp dir if it already exists
Done https://github.com/NethermindEth/eigenlayer/pull/98/commits/f4c6be6d7473372dce31bb83ef170d1fee555ec2

2023-10-10 17:52 UTC, AntiD2ta commented on e2e/local_update_test.go
> +			updateError = runCommand(t, egnPath, "local-update", "--no-prompt", "--option.test-option-hidden", "12345678", "mock-avs-default", pkgDir)
You are not understanding me. For `v5.4.0` you used `test-option-enum-hidden`, and for `v5.5.1` you are not.

2023-10-13 14:43 UTC, adriantpaez commented on e2e/local_update_test.go
> +			assert.NoError(t, updateError, "update command should succeed")
Done https://github.com/NethermindEth/eigenlayer/pull/98/commits/ab7690e626656777c10486143061d8e09ed717f5

2023-10-13 15:06 UTC, AntiD2ta approved these changes

2023-10-16 10:50 UTC, merged